name = "yuubnet"
compatibility_date = "2025-01-29"
compatibility_flags = [ "nodejs_compat" ]

[vars]
ANALYTICS_WORKER_URL = "https://yuubnet-analytics.ipai-mc.workers.dev"
ASSET_FETCH_WORKER_URL = "https://yuubnet-asset-fetch.ipai-mc.workers.dev"