name = "yuubnet"
compatibility_date = "2024-02-09"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next"

# Environment variables
[vars]
NODE_ENV = "production"

[dev]
port = 8788
local_protocol = "http"